#Config file for FileTracking

lib:
    libDir: '.'

remote:
  libDir: 'python'
  host:
    sshKeyFile: '/home/inty/.ssh/id_rsa'
    hostName: 'hadoop-master'
    protocol: 'ssh'
    username: 'hduser'
    pass: ''
    port: 'default'

features:
    file: 'installedFeatures.txt'

repos:
    folder: '../.repos/'