#Config file for FileTracking
lib:
  libDir: '.'

remote:
  libDir: 'python'
  host: 'hadoop-master'
    protocol: 'ssh'
    user: 'python'
    pass: 'python'

features:
  file: 'installedFeatures.txt'

repos:
  folder: '../.repos/'